import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { AppConfig } from "./types";

function shellQuote(value: string) {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

export function shellIntegration(config: AppConfig) {
  const lines = [
    "# Generated by claude-account-switcher. Do not edit by hand.",
    "",
  ];
  for (const profile of config.profiles) {
    lines.push(`${profile.alias}() {`);
    lines.push(`  cca run ${shellQuote(profile.name)} -- "$@"`);
    lines.push("}");
    lines.push("");
  }
  return lines.join("\n");
}

export async function writeShellIntegration(config: AppConfig) {
  await mkdir(dirname(config.shellIntegrationPath), { recursive: true });
  await writeFile(config.shellIntegrationPath, shellIntegration(config), "utf8");
}

