import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { AppConfig } from "./types";
import { profileDir } from "./config";

function shellQuote(value: string) {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

export function shellIntegration(config: AppConfig) {
  const lines = [
    "# Generated by claude-account-switcher. Do not edit by hand.",
    "# Normal profile commands route directly to Claude with no runtime wrapper.",
    "# MCP commands use cca run-managed so shared MCP config and OAuth are merged.",
    "",
  ];
  for (const profile of config.profiles) {
    const root = profileDir(config, profile.name);
    lines.push(`${profile.alias}() {`);
    lines.push(`  case "$1" in`);
    lines.push(`    mcp) cca run-managed ${shellQuote(profile.name)} -- "$@" ;;`);
    lines.push(`    *) CLAUDE_CONFIG_DIR=${shellQuote(root)} ${shellQuote(config.claudePath)} "$@" ;;`);
    lines.push(`  esac`);
    lines.push("}");
    lines.push("");
  }
  return lines.join("\n");
}

export async function writeShellIntegration(config: AppConfig) {
  await mkdir(dirname(config.shellIntegrationPath), { recursive: true });
  await writeFile(config.shellIntegrationPath, shellIntegration(config), "utf8");
}
